import type { SeasonalHeroItem, SeasonalHomeData } from './types';

type MockSeasonalSeed = {
  id: string;
  month: number;
  monthLabel: string;
  name: string;
  category: string;
  headline: string;
  subcopy: string;
  accentColor: string;
  accentSoftColor: string;
  orbStrongColor: string;
  orbSoftColor: string;
  stats: Array<{
    label: string;
    value: string;
  }>;
};

const FALLBACK_ITEMS: MockSeasonalSeed[] = [
  {
    id: 'fallback-strawberry',
    month: 1,
    monthLabel: '오늘의 제철',
    name: '딸기',
    category: '과일',
    headline: '가장 향이 좋은 재료부터 둘러보세요',
    subcopy: '영상, 이미지, 레시피, 근처 가게를 한 번에 이어보는 홈 섹션 시안입니다.',
    accentColor: '#C84F6F',
    accentSoftColor: '#FAE6EB',
    orbStrongColor: '#F2BBC8',
    orbSoftColor: '#F8D9E0',
    stats: [
      { label: '영상', value: '18' },
      { label: '이미지', value: '42' },
      { label: '근처', value: '6곳' },
    ],
  },
  {
    id: 'fallback-oyster',
    month: 1,
    monthLabel: '오늘의 제철',
    name: '굴',
    category: '해산물',
    headline: '차가운 계절에 가장 진한 풍미를 보여줍니다',
    subcopy: '제철 재료를 고르면 아래 영상과 이미지 흐름도 같은 맥락으로 이어집니다.',
    accentColor: '#577492',
    accentSoftColor: '#E8EEF4',
    orbStrongColor: '#C8D6E4',
    orbSoftColor: '#DCE7F0',
    stats: [
      { label: '영상', value: '11' },
      { label: '이미지', value: '25' },
      { label: '근처', value: '4곳' },
    ],
  },
  {
    id: 'fallback-spinach',
    month: 1,
    monthLabel: '오늘의 제철',
    name: '시금치',
    category: '채소',
    headline: '짧게 보기 좋은 초록의 계절 장면을 묶었습니다',
    subcopy: '과하지 않은 상단 에디토리얼 섹션으로 홈 첫 화면의 맥락을 잡아주는 용도입니다.',
    accentColor: '#4B8B60',
    accentSoftColor: '#E6F2E9',
    orbStrongColor: '#BFDDC6',
    orbSoftColor: '#D9EEDD',
    stats: [
      { label: '영상', value: '9' },
      { label: '이미지', value: '21' },
      { label: '근처', value: '3곳' },
    ],
  },
];

const SEASONAL_ITEMS_BY_MONTH: Record<number, MockSeasonalSeed[]> = {
  1: [
    {
      id: 'jan-strawberry',
      month: 1,
      monthLabel: '1월의 제철',
      name: '딸기',
      category: '과일',
      headline: '한겨울에도 가장 화사하게 열리는 붉은 장면',
      subcopy: '달고 향이 오른 딸기를 중심으로 영상, 이미지, 레시피, 근처 가게 흐름을 연결합니다.',
      accentColor: '#C84F6F',
      accentSoftColor: '#FAE6EB',
      orbStrongColor: '#F2BBC8',
      orbSoftColor: '#F8D9E0',
      stats: [
        { label: '영상', value: '18' },
        { label: '이미지', value: '42' },
        { label: '근처', value: '6곳' },
      ],
    },
    {
      id: 'jan-oyster',
      month: 1,
      monthLabel: '1월의 제철',
      name: '굴',
      category: '해산물',
      headline: '차갑고 선명한 바다 풍미가 가장 깊어지는 시기',
      subcopy: '짧은 영상과 매장 흐름을 묶어 계절감이 강한 먹거리 탐색 경험을 만듭니다.',
      accentColor: '#577492',
      accentSoftColor: '#E8EEF4',
      orbStrongColor: '#C8D6E4',
      orbSoftColor: '#DCE7F0',
      stats: [
        { label: '영상', value: '11' },
        { label: '이미지', value: '25' },
        { label: '근처', value: '4곳' },
      ],
    },
    {
      id: 'jan-spinach',
      month: 1,
      monthLabel: '1월의 제철',
      name: '시금치',
      category: '채소',
      headline: '차갑게 오른 단맛이 가장 또렷한 잎채소',
      subcopy: '신선한 초록 톤으로 홈 상단을 정리하면서도 아래 콘텐츠와 자연스럽게 연결됩니다.',
      accentColor: '#4B8B60',
      accentSoftColor: '#E6F2E9',
      orbStrongColor: '#BFDDC6',
      orbSoftColor: '#D9EEDD',
      stats: [
        { label: '영상', value: '9' },
        { label: '이미지', value: '21' },
        { label: '근처', value: '3곳' },
      ],
    },
  ],
  2: [
    {
      id: 'feb-strawberry',
      month: 2,
      monthLabel: '2월의 제철',
      name: '딸기',
      category: '과일',
      headline: '향과 산미, 단맛 균형이 가장 예쁜 시기',
      subcopy: '밝은 붉은 톤을 기준으로 시즌 콘텐츠를 정렬하는 홈 섹션 시안입니다.',
      accentColor: '#D15776',
      accentSoftColor: '#FBE7EC',
      orbStrongColor: '#F1BCCB',
      orbSoftColor: '#F7D8E1',
      stats: [
        { label: '영상', value: '17' },
        { label: '이미지', value: '39' },
        { label: '근처', value: '5곳' },
      ],
    },
    {
      id: 'feb-seaweed',
      month: 2,
      monthLabel: '2월의 제철',
      name: '매생이',
      category: '해조류',
      headline: '짙은 바다 향을 가장 부드럽게 느낄 수 있습니다',
      subcopy: '겨울 시즌의 촉감과 온도를 전달하는 재료를 영상과 이미지 우선으로 묶습니다.',
      accentColor: '#2C7366',
      accentSoftColor: '#E0F0EB',
      orbStrongColor: '#A8CEC4',
      orbSoftColor: '#CFE5DF',
      stats: [
        { label: '영상', value: '8' },
        { label: '이미지', value: '16' },
        { label: '근처', value: '2곳' },
      ],
    },
    {
      id: 'feb-yellowtail',
      month: 2,
      monthLabel: '2월의 제철',
      name: '방어',
      category: '생선',
      headline: '기름이 오르는 시기의 선명한 결을 보여줍니다',
      subcopy: '근처 가게 탐색과 레시피 전환까지 자연스럽게 이어질 수 있는 대표 아이템입니다.',
      accentColor: '#496C8F',
      accentSoftColor: '#E5EDF5',
      orbStrongColor: '#BDD0E4',
      orbSoftColor: '#D7E4F1',
      stats: [
        { label: '영상', value: '12' },
        { label: '이미지', value: '24' },
        { label: '근처', value: '4곳' },
      ],
    },
  ],
  3: [
    {
      id: 'mar-springcabbage',
      month: 3,
      monthLabel: '3월의 제철',
      name: '봄동',
      category: '채소',
      headline: '봄의 가장 부드러운 초록을 먼저 보여줍니다',
      subcopy: '계절이 바뀌는 타이밍에 홈 첫 화면의 톤을 새롭게 전환하는 대표 재료입니다.',
      accentColor: '#5A8D52',
      accentSoftColor: '#EAF4E4',
      orbStrongColor: '#C7DEBC',
      orbSoftColor: '#DDECD5',
      stats: [
        { label: '영상', value: '10' },
        { label: '이미지', value: '28' },
        { label: '근처', value: '5곳' },
      ],
    },
    {
      id: 'mar-strawberry',
      month: 3,
      monthLabel: '3월의 제철',
      name: '딸기',
      category: '과일',
      headline: '봄 초입의 달콤한 컬러를 가장 먼저 채웁니다',
      subcopy: '짧은 콘텐츠 흐름과 레시피 전환이 모두 자연스러운 홈 상단 시나리오입니다.',
      accentColor: '#CE5C78',
      accentSoftColor: '#FCE8ED',
      orbStrongColor: '#F2BFCB',
      orbSoftColor: '#F6D6E0',
      stats: [
        { label: '영상', value: '16' },
        { label: '이미지', value: '37' },
        { label: '근처', value: '6곳' },
      ],
    },
    {
      id: 'mar-webfoot-octopus',
      month: 3,
      monthLabel: '3월의 제철',
      name: '주꾸미',
      category: '해산물',
      headline: '부드럽고 탱글한 식감이 가장 살아나는 시기',
      subcopy: '미니맵과 매장 연결에 특히 강한 제철 재료로 활용하기 좋습니다.',
      accentColor: '#A05F5B',
      accentSoftColor: '#F5E8E5',
      orbStrongColor: '#DFC4BE',
      orbSoftColor: '#EED9D4',
      stats: [
        { label: '영상', value: '9' },
        { label: '이미지', value: '19' },
        { label: '근처', value: '4곳' },
      ],
    },
  ],
  4: [
    {
      id: 'apr-garlicshoot',
      month: 4,
      monthLabel: '4월의 제철',
      name: '마늘쫑',
      category: '채소',
      headline: '아삭한 초록의 질감이 화면에서 가장 잘 살아납니다',
      subcopy: '밝은 화이트 홈과 상성이 좋은 계절 재료로 상단 시각 언어를 정리할 수 있습니다.',
      accentColor: '#5E9A62',
      accentSoftColor: '#E8F5E7',
      orbStrongColor: '#C4E0C5',
      orbSoftColor: '#DBEEDD',
      stats: [
        { label: '영상', value: '8' },
        { label: '이미지', value: '17' },
        { label: '근처', value: '3곳' },
      ],
    },
    {
      id: 'apr-squid',
      month: 4,
      monthLabel: '4월의 제철',
      name: '한치',
      category: '해산물',
      headline: '봄 바다 특유의 맑은 질감이 가장 깨끗하게 보입니다',
      subcopy: '미니맵과 함께 묶어 가게 탐색으로 이어주기 좋은 시즌 재료입니다.',
      accentColor: '#4F6E88',
      accentSoftColor: '#E7EEF4',
      orbStrongColor: '#C6D5E1',
      orbSoftColor: '#DCE7EF',
      stats: [
        { label: '영상', value: '7' },
        { label: '이미지', value: '15' },
        { label: '근처', value: '4곳' },
      ],
    },
    {
      id: 'apr-strawberry',
      month: 4,
      monthLabel: '4월의 제철',
      name: '딸기',
      category: '과일',
      headline: '봄 끝자락까지 가장 화사한 색을 유지합니다',
      subcopy: '상단 편집 카드에서 음식보다 장면 중심으로 풀어내기 좋은 대표 과일입니다.',
      accentColor: '#D15A72',
      accentSoftColor: '#FCE8EC',
      orbStrongColor: '#F1C0CB',
      orbSoftColor: '#F7D9E1',
      stats: [
        { label: '영상', value: '14' },
        { label: '이미지', value: '31' },
        { label: '근처', value: '5곳' },
      ],
    },
  ],
  5: [
    {
      id: 'may-korean-melon',
      month: 5,
      monthLabel: '5월의 제철',
      name: '참외',
      category: '과일',
      headline: '이번 주 가장 산뜻한 단맛을 먼저 보여줍니다',
      subcopy: '제철 장면, 레시피, 근처 가게를 하나의 리듬으로 연결하는 홈 상단 시안입니다.',
      accentColor: '#A7C84B',
      accentSoftColor: '#F1F8DB',
      orbStrongColor: '#D5E79B',
      orbSoftColor: '#E8F3C1',
      stats: [
        { label: '영상', value: '21' },
        { label: '이미지', value: '54' },
        { label: '근처', value: '8곳' },
      ],
    },
    {
      id: 'may-plum',
      month: 5,
      monthLabel: '5월의 제철',
      name: '매실',
      category: '과일',
      headline: '초여름 직전의 산미와 초록 톤을 가장 예쁘게 담습니다',
      subcopy: '계절 재료 중심 홈을 만들 때 이미지와 레시피로 이어지기 좋은 대표 재료입니다.',
      accentColor: '#4E9B7C',
      accentSoftColor: '#E4F4EE',
      orbStrongColor: '#BCE0D0',
      orbSoftColor: '#D9EEE5',
      stats: [
        { label: '영상', value: '13' },
        { label: '이미지', value: '29' },
        { label: '근처', value: '4곳' },
      ],
    },
    {
      id: 'may-hairtail',
      month: 5,
      monthLabel: '5월의 제철',
      name: '병어',
      category: '생선',
      headline: '은은한 은빛 결이 가장 고급스럽게 살아나는 시기',
      subcopy: '화이트 중심 홈 레이아웃과 잘 맞는 차가운 금속 톤을 가진 시즌 식재료입니다.',
      accentColor: '#6D879F',
      accentSoftColor: '#E8EEF4',
      orbStrongColor: '#CCD9E4',
      orbSoftColor: '#DDE7EF',
      stats: [
        { label: '영상', value: '9' },
        { label: '이미지', value: '18' },
        { label: '근처', value: '3곳' },
      ],
    },
    {
      id: 'may-eel',
      month: 5,
      monthLabel: '5월의 제철',
      name: '장어',
      category: '해산물',
      headline: '기운을 끌어올리는 초여름 전야의 진한 풍미',
      subcopy: '영상 소비와 근처 매장 탐색을 동시에 자극하는 대표 보양 시즌 아이템입니다.',
      accentColor: '#9A6848',
      accentSoftColor: '#F6EBDD',
      orbStrongColor: '#E5C9AF',
      orbSoftColor: '#F0DEC9',
      stats: [
        { label: '영상', value: '15' },
        { label: '이미지', value: '26' },
        { label: '근처', value: '7곳' },
      ],
    },
  ],
  6: [
    {
      id: 'jun-apricot',
      month: 6,
      monthLabel: '6월의 제철',
      name: '살구',
      category: '과일',
      headline: '짧고 진한 여름 초입의 향을 담기 좋은 시기',
      subcopy: '색이 강한 재료를 이용해 홈 첫 화면의 시선을 부드럽게 끌어오는 구성입니다.',
      accentColor: '#E08F55',
      accentSoftColor: '#FCEBDD',
      orbStrongColor: '#F2C9A7',
      orbSoftColor: '#F7DDC4',
      stats: [
        { label: '영상', value: '10' },
        { label: '이미지', value: '23' },
        { label: '근처', value: '3곳' },
      ],
    },
    {
      id: 'jun-peach',
      month: 6,
      monthLabel: '6월의 제철',
      name: '복숭아',
      category: '과일',
      headline: '여름의 부드러운 핑크 톤을 가장 풍성하게 채웁니다',
      subcopy: '이미지와 영상 미감이 모두 강한 재료라 홈 상단 히어로에 잘 맞습니다.',
      accentColor: '#D77983',
      accentSoftColor: '#FCE8EB',
      orbStrongColor: '#F0BEC5',
      orbSoftColor: '#F7D9DE',
      stats: [
        { label: '영상', value: '19' },
        { label: '이미지', value: '47' },
        { label: '근처', value: '6곳' },
      ],
    },
    {
      id: 'jun-sea-squirt',
      month: 6,
      monthLabel: '6월의 제철',
      name: '멍게',
      category: '해산물',
      headline: '차갑고 짠 바다 향이 가장 또렷하게 서는 시기',
      subcopy: '근처 가게 추천과 연동하기 좋고, 계절감을 강하게 주는 재료입니다.',
      accentColor: '#B2644A',
      accentSoftColor: '#F8E6DE',
      orbStrongColor: '#E6B9A8',
      orbSoftColor: '#F0D4C8',
      stats: [
        { label: '영상', value: '7' },
        { label: '이미지', value: '14' },
        { label: '근처', value: '2곳' },
      ],
    },
  ],
  7: [
    {
      id: 'jul-watermelon',
      month: 7,
      monthLabel: '7월의 제철',
      name: '수박',
      category: '과일',
      headline: '여름의 가장 큰 장면을 상단에서 바로 보여줍니다',
      subcopy: '크고 시원한 과일 이미지는 홈 첫 화면의 시각 리듬을 강하게 잡아줍니다.',
      accentColor: '#E15F63',
      accentSoftColor: '#FCE5E6',
      orbStrongColor: '#F2B8BA',
      orbSoftColor: '#F7D5D7',
      stats: [
        { label: '영상', value: '22' },
        { label: '이미지', value: '58' },
        { label: '근처', value: '6곳' },
      ],
    },
    {
      id: 'jul-cucumber',
      month: 7,
      monthLabel: '7월의 제철',
      name: '오이',
      category: '채소',
      headline: '시원한 초록의 결을 가장 가볍게 보여줄 수 있습니다',
      subcopy: '화이트 홈에 신선한 온도를 주는 보조 제철 재료로 적합합니다.',
      accentColor: '#5A9C68',
      accentSoftColor: '#E6F4E8',
      orbStrongColor: '#C2E0C8',
      orbSoftColor: '#DDEEDF',
      stats: [
        { label: '영상', value: '8' },
        { label: '이미지', value: '17' },
        { label: '근처', value: '3곳' },
      ],
    },
    {
      id: 'jul-sea-bass',
      month: 7,
      monthLabel: '7월의 제철',
      name: '농어',
      category: '생선',
      headline: '한여름의 단단한 살결을 가장 깔끔하게 담는 시즌',
      subcopy: '미니맵과 함께 매장 탐색으로 연결하기 좋은 제철 생선입니다.',
      accentColor: '#65839D',
      accentSoftColor: '#E7EEF3',
      orbStrongColor: '#CBD9E3',
      orbSoftColor: '#DCE6EE',
      stats: [
        { label: '영상', value: '9' },
        { label: '이미지', value: '18' },
        { label: '근처', value: '4곳' },
      ],
    },
  ],
  8: [
    {
      id: 'aug-peach',
      month: 8,
      monthLabel: '8월의 제철',
      name: '복숭아',
      category: '과일',
      headline: '한여름의 향을 가장 풍성하게 완성하는 대표 과일',
      subcopy: '영상과 이미지 모두 미감이 좋아 계절 홈의 히어로 재료로 가장 안정적입니다.',
      accentColor: '#D97A8C',
      accentSoftColor: '#FCE9ED',
      orbStrongColor: '#F0C1CA',
      orbSoftColor: '#F8DCE2',
      stats: [
        { label: '영상', value: '20' },
        { label: '이미지', value: '49' },
        { label: '근처', value: '5곳' },
      ],
    },
    {
      id: 'aug-corn',
      month: 8,
      monthLabel: '8월의 제철',
      name: '옥수수',
      category: '곡물',
      headline: '달고 고소한 질감이 가장 단단하게 올라오는 시기',
      subcopy: '부드러운 노란 톤으로 제철 카드의 시각 중심을 만들기 좋습니다.',
      accentColor: '#D5AE4A',
      accentSoftColor: '#FBF2D8',
      orbStrongColor: '#EFD89A',
      orbSoftColor: '#F6E8C2',
      stats: [
        { label: '영상', value: '12' },
        { label: '이미지', value: '24' },
        { label: '근처', value: '4곳' },
      ],
    },
    {
      id: 'aug-abalone',
      month: 8,
      monthLabel: '8월의 제철',
      name: '전복',
      category: '해산물',
      headline: '초여름을 지나 깊어진 감칠맛이 가장 안정적인 시기',
      subcopy: '고급스러운 매장 탐색과 함께 묶기 좋은 대표 시즌 해산물입니다.',
      accentColor: '#507A6D',
      accentSoftColor: '#E5F1ED',
      orbStrongColor: '#B9D7CD',
      orbSoftColor: '#D8EAE4',
      stats: [
        { label: '영상', value: '11' },
        { label: '이미지', value: '22' },
        { label: '근처', value: '6곳' },
      ],
    },
  ],
  9: [
    {
      id: 'sep-pear',
      month: 9,
      monthLabel: '9월의 제철',
      name: '배',
      category: '과일',
      headline: '가을의 맑은 단맛을 가장 선명하게 보여주는 과일',
      subcopy: '깨끗한 흰 톤과 어울려 홈 첫 화면에 계절 전환감을 주기 좋습니다.',
      accentColor: '#B79F56',
      accentSoftColor: '#F8F1DC',
      orbStrongColor: '#E4D6A2',
      orbSoftColor: '#F1E8C4',
      stats: [
        { label: '영상', value: '16' },
        { label: '이미지', value: '35' },
        { label: '근처', value: '5곳' },
      ],
    },
    {
      id: 'sep-matsutake',
      month: 9,
      monthLabel: '9월의 제철',
      name: '송이',
      category: '버섯',
      headline: '짧지만 가장 강한 향을 가진 가을의 시작점',
      subcopy: '가을 시즌의 특별함을 강조하는 편집 카드로 적합한 재료입니다.',
      accentColor: '#9A734E',
      accentSoftColor: '#F6EBE0',
      orbStrongColor: '#DFC8B1',
      orbSoftColor: '#ECDED1',
      stats: [
        { label: '영상', value: '8' },
        { label: '이미지', value: '14' },
        { label: '근처', value: '2곳' },
      ],
    },
    {
      id: 'sep-saury',
      month: 9,
      monthLabel: '9월의 제철',
      name: '전어',
      category: '생선',
      headline: '가을 바다 특유의 반짝임을 가장 잘 품는 생선',
      subcopy: '영상 섹션과 미니맵 섹션을 함께 묶는 대표 가을 재료로 쓰기 좋습니다.',
      accentColor: '#617A95',
      accentSoftColor: '#E8EEF3',
      orbStrongColor: '#C9D5E0',
      orbSoftColor: '#DCE5ED',
      stats: [
        { label: '영상', value: '10' },
        { label: '이미지', value: '19' },
        { label: '근처', value: '4곳' },
      ],
    },
  ],
  10: [
    {
      id: 'oct-persimmon',
      month: 10,
      monthLabel: '10월의 제철',
      name: '감',
      category: '과일',
      headline: '부드러운 주황 톤으로 계절감이 가장 선명합니다',
      subcopy: '시각적으로 강한 시즌 과일이라 홈 상단의 존재감을 만들기 쉽습니다.',
      accentColor: '#D97942',
      accentSoftColor: '#FCE9DD',
      orbStrongColor: '#F1C4A6',
      orbSoftColor: '#F7DBC6',
      stats: [
        { label: '영상', value: '18' },
        { label: '이미지', value: '41' },
        { label: '근처', value: '5곳' },
      ],
    },
    {
      id: 'oct-crab',
      month: 10,
      monthLabel: '10월의 제철',
      name: '꽃게',
      category: '해산물',
      headline: '가을 바다의 묵직한 감칠맛을 가장 강하게 보여줍니다',
      subcopy: '미니맵과 연결했을 때 탐색 동기를 만들기 좋은 대표 시즌 식재료입니다.',
      accentColor: '#B16159',
      accentSoftColor: '#F8E7E4',
      orbStrongColor: '#E4B7AF',
      orbSoftColor: '#EFD5D0',
      stats: [
        { label: '영상', value: '13' },
        { label: '이미지', value: '27' },
        { label: '근처', value: '6곳' },
      ],
    },
    {
      id: 'oct-mushroom',
      month: 10,
      monthLabel: '10월의 제철',
      name: '표고버섯',
      category: '버섯',
      headline: '건조한 계절에 향과 텍스처가 가장 깊어지는 시기',
      subcopy: '레시피 전환에 강하고, 따뜻한 가을 분위기를 자연스럽게 만들어줍니다.',
      accentColor: '#8B6A4B',
      accentSoftColor: '#F4EADF',
      orbStrongColor: '#DBC8B3',
      orbSoftColor: '#EBDDCE',
      stats: [
        { label: '영상', value: '7' },
        { label: '이미지', value: '15' },
        { label: '근처', value: '3곳' },
      ],
    },
  ],
  11: [
    {
      id: 'nov-radish',
      month: 11,
      monthLabel: '11월의 제철',
      name: '무',
      category: '채소',
      headline: '차가워질수록 단맛이 단단해지는 겨울 전초전의 재료',
      subcopy: '심플한 화이트 홈과 잘 맞는 깨끗한 식재료 이미지로 상단을 정리할 수 있습니다.',
      accentColor: '#7FAE74',
      accentSoftColor: '#EDF6E9',
      orbStrongColor: '#CFE3C8',
      orbSoftColor: '#E3EFE0',
      stats: [
        { label: '영상', value: '9' },
        { label: '이미지', value: '18' },
        { label: '근처', value: '4곳' },
      ],
    },
    {
      id: 'nov-cod',
      month: 11,
      monthLabel: '11월의 제철',
      name: '대구',
      category: '생선',
      headline: '맑은 살결이 가장 차분하고 또렷하게 살아납니다',
      subcopy: '겨울 시작점의 매장 탐색과 레시피 전환을 자연스럽게 연결하기 좋습니다.',
      accentColor: '#5E7790',
      accentSoftColor: '#E8EEF3',
      orbStrongColor: '#C8D4DF',
      orbSoftColor: '#DCE5EC',
      stats: [
        { label: '영상', value: '10' },
        { label: '이미지', value: '20' },
        { label: '근처', value: '5곳' },
      ],
    },
    {
      id: 'nov-apple',
      month: 11,
      monthLabel: '11월의 제철',
      name: '사과',
      category: '과일',
      headline: '늦가을의 선명한 붉은 톤을 가장 안정적으로 채워줍니다',
      subcopy: '영상과 이미지의 시각 집중도를 동시에 올리기 좋은 제철 과일입니다.',
      accentColor: '#C65A50',
      accentSoftColor: '#F9E7E4',
      orbStrongColor: '#E9BAB3',
      orbSoftColor: '#F2D5D1',
      stats: [
        { label: '영상', value: '15' },
        { label: '이미지', value: '32' },
        { label: '근처', value: '4곳' },
      ],
    },
  ],
  12: [
    {
      id: 'dec-tangerine',
      month: 12,
      monthLabel: '12월의 제철',
      name: '귤',
      category: '과일',
      headline: '겨울 홈 화면에 가장 즉각적인 밝기를 더하는 재료',
      subcopy: '연말 시즌의 감도를 높이면서도 무겁지 않게 홈 첫 화면을 정리할 수 있습니다.',
      accentColor: '#E08A40',
      accentSoftColor: '#FCEBDD',
      orbStrongColor: '#F3C79E',
      orbSoftColor: '#F8DEC4',
      stats: [
        { label: '영상', value: '20' },
        { label: '이미지', value: '46' },
        { label: '근처', value: '5곳' },
      ],
    },
    {
      id: 'dec-oyster',
      month: 12,
      monthLabel: '12월의 제철',
      name: '굴',
      category: '해산물',
      headline: '차가운 바다 향이 가장 단단하게 고정되는 절정기',
      subcopy: '매장 탐색과 짧은 먹거리 영상 소비를 동시에 자극하기 좋은 겨울 대표 재료입니다.',
      accentColor: '#587694',
      accentSoftColor: '#E7EEF4',
      orbStrongColor: '#C9D8E4',
      orbSoftColor: '#DDE7EF',
      stats: [
        { label: '영상', value: '12' },
        { label: '이미지', value: '28' },
        { label: '근처', value: '4곳' },
      ],
    },
    {
      id: 'dec-cabbage',
      month: 12,
      monthLabel: '12월의 제철',
      name: '배추',
      category: '채소',
      headline: '겨울의 밀도와 온기를 동시에 보여주는 기본 재료',
      subcopy: '레시피와 생활감 있는 콘텐츠 연결에 강한 시즌 채소입니다.',
      accentColor: '#769A58',
      accentSoftColor: '#EEF5E4',
      orbStrongColor: '#CFDEBE',
      orbSoftColor: '#E2ECD6',
      stats: [
        { label: '영상', value: '8' },
        { label: '이미지', value: '17' },
        { label: '근처', value: '3곳' },
      ],
    },
  ],
};

const getSeasonalSeedsForMonth = (month: number): MockSeasonalSeed[] => {
  const items = SEASONAL_ITEMS_BY_MONTH[month];
  if (items && items.length > 0) {
    return items;
  }
  return FALLBACK_ITEMS;
};

const seedToHeroItem = (seed: MockSeasonalSeed, index: number): SeasonalHeroItem => ({
  seasonalFoodId: index + 1,
  month: seed.month,
  monthLabel: seed.monthLabel,
  seasonalTerm: seed.monthLabel.replace('의 제철', ''),
  name: seed.name,
  category: seed.category,
  headline: seed.headline,
  subcopy: seed.subcopy,
  accentColor: seed.accentColor,
  accentSoftColor: seed.accentSoftColor,
  orbStrongColor: seed.orbStrongColor,
  orbSoftColor: seed.orbSoftColor,
  stats: seed.stats,
});

export const getSeasonalHeroItemsForMonth = (month: number): SeasonalHeroItem[] =>
  getSeasonalSeedsForMonth(month).map((seed, index) => seedToHeroItem(seed, index));

export const buildMockSeasonalHomeDataForMonth = (
  month: number,
  seasonalFoodId?: number | null,
): SeasonalHomeData => {
  const heroes = getSeasonalHeroItemsForMonth(month);
  const activeHero =
    heroes.find((hero) => hero.seasonalFoodId === seasonalFoodId) ?? heroes[0];

  const chips = heroes.map((hero) => ({
    seasonalFoodId: hero.seasonalFoodId,
    foodName: hero.name,
    isActive: hero.seasonalFoodId === activeHero.seasonalFoodId,
  }));

  return {
    basisInfo: {
      basis: 'MONTH',
      referenceDate: null,
      month,
      seasonalTerm: activeHero.seasonalTerm ?? null,
    },
    hero: activeHero,
    chips,
    foods: heroes.map((hero) => ({
      seasonalFoodId: hero.seasonalFoodId,
      seasonalTerm: hero.seasonalTerm ?? null,
      month: hero.month,
      foodName: hero.name,
      category: hero.category,
      cardImageUrl: hero.cardImageUrl ?? null,
      cardImageMobileUrl: hero.cardImageMobileUrl ?? null,
    })),
  };
};
